export const SET_DISPLAYED_INGREDIENT: 'SET_DISPLAYED_INGREDIENT' = 'SET_DISPLAYED_INGREDIENT';
export const DELETE_DISPLAYED_INGREDIENT: 'DELETE_DISPLAYED_INGREDIENT' = 'DELETE_DISPLAYED_INGREDIENT';
