export const INCREASE_INGREDIENT: 'INCREASE_INGREDIENT'  = 'INCREASE_INGREDIENT';
export const INCREASE_BUN: 'INCREASE_BUN' = 'INCREASE_BUN';
export const DECREASE_INGREDIENT: 'DECREASE_INGREDIENT' = 'DECREASE_INGREDIENT';
export const GET_INGRIDIENTS_REQUEST: 'GET_INGRIDIENTS_REQUEST' = 'GET_INGRIDIENTS_REQUEST';
export const GET_INGRIDIENTS_SUCCESS: 'GET_INGRIDIENTS_SUCCESS' = 'GET_INGRIDIENTS_SUCCESS';
export const GET_INGRIDIENTS_FAILED: 'GET_INGRIDIENTS_FAILED' = 'GET_INGRIDIENTS_FAILED';
export const SET_MENU_TAB: 'SET_MENU_TAB' = 'SET_MENU_TAB';
